### ISSUE TITLE
Park does not account for movement due to tracking

### ISSUE THREAD

**Issue by EorEquis** [ClutchplateDude/OpenAstroTracker#14]
Park should return the mount to its startup point, but does not if no slews were performed.

Example :

* Power up mount, pointed at pole, complete startup config (HA, etc)
* Leave mount untouched for 1 hour.
* RA Ring has rotated one hour.
* :hP does not return mount to startup position
* Unpark mount
* Slew 1 hr in RA.
* :hP returns mount to previous position (One hour of ring rotation), not startup position.

**Comment by ClutchplateDude** [comment]
I'll have to try this, but this should work, I mean the code does account for tracking. What won't work is if you leave it parked too long since HA does not increase.....hmmm. I think I need to keep track of how long it was parked and then increase HA by that amount when it's unparked. But your scenario should work. if it doesn't remain parked too long.

**Comment by EorEquis** [comment]
hrm...I'll retest and document more thoroughly, to be sure.

**Comment by EorEquis** [comment]
There's definitely SOMETHING going on here.  Seems like most of the time it's fine...but every so often I can ask it to park, and it just parks as is where is.
